; Copyright (c) 2007 Mark Longstaff-Tyrrell All Rights Reserved.
; DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
;
; This code is free software; you can redistribute it and/or modify it
; under the terms of the GNU General Public License version 3 only, as
; published by the Free Software Foundation.
;
;  This code is distributed in the hope that it will be useful,
;  but WITHOUT ANY WARRANTY; without even the implied warranty of
;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;  GNU General Public License for more details.
;
;  You should have received a copy of the GNU General Public License
;  along with this work.  If not, see <http://www.gnu.org/licenses/>.


AL_KEYPRESSED

	CASENOT AL_MODE,AL_SET
	RETURN

	; IF SET KEY PRESSED THEN CANCEL ALARM
	MOVLW	SET_KEY
	SUBWF	IN_KEY,W
	BTFSS	STATUS,Z
	GOTO	AK_K1
	
	MOVLW	0XFF
	MOVWF	A_HOUR
	MOVWF	A_MIN
	MOVLF	AL_MODE,AL_SHOW
	RETURN

AK_K1

	CALL	SET_DIGIT

	; IF 'W' IS ZERO, THEN WE'RE DONE
	ANDLW	0XFF
	BTFSS	STATUS,Z
	RETURN

	; UPDATE ALARM FROM DISPLAY
	CALL COPY_ALARM_DISPLAY

	; BACK TO ALARM MODE
	MOVLF AL_MODE,AL_SHOW
	RETURN


COPY_ALARM_DISPLAY

	; HOURS
	MOVLW	DIG3
	CALL COPY_DIGIT
	MOVWF	A_HOUR

	; HOURS
	MOVLW	DIG5
	CALL COPY_DIGIT
	MOVWF	A_MIN

	RETURN

AL_LONGKEYPRESSED

	CASENOT AL_MODE,AL_SHOW
	RETURN

	CASE	IN_KEY,SET_KEY
	GOTO	AL_LKP1

	; show s/w version
	CASE	IN_KEY,0
	GOTO	AL_LKP2

	RETURN

AL_LKP1

	MOVLF	CURSOR,0X02
	MOVLF	AL_MODE,AL_SET
	; SET UP DISPLAY FOR TIME SETTING
	MOVLF	DIG1,LETTER_A
	MOVLF	DIG2,LETTER_L
	MOVLF	DIG3,UNDERSCORE
	MOVLF	DIG4,UNDERSCORE
	MOVLF	DIG5,UNDERSCORE
	MOVLF	DIG6,UNDERSCORE
	MOVLF	DIG7,SET_COLON
	RETURN

AL_LKP2

	MOVLF	AL_MODE,AL_VER

	MOVLF	DIG1,LETTER_R
	MOVLF	DIG2,LETTER_E

	; H/W VERSION
	MOVLF	DIG3,BLANK
	MOVLF	DIG4,SYSTEM_VERSION

	; S/W VERSION
	MOVLF	DIG5,SOFTWARE_VERSION_HI
	MOVLF	DIG6,SOFTWARE_VERSION_LO

	MOVLF	DIG7,VER_COLON

	RETURN
